### ISSUE TITLE
python 3.10 image

### ISSUE THREAD

**Issue by arnonmoscona** [tiangolo/uvicorn-gunicorn-docker#139]
Related to https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/129
Can we expect a Python 3.10 docker image any time soon?

**Comment by thomasleveil** [comment]
bumping, as per [PEP 596](https://peps.python.org/pep-0596/), Python 3.9 does not profit from any bug fixes since 2022-05-17 _(although it still has security fixes until October 2025)_.

Having this project support Python 3.10 which is the current stable version would be very nice

**Comment by thomasleveil** [comment]
Update : Python 3.11 is now the stable release. Python 3.10 still have security & bug support

![image](https://user-images.githubusercontent.com/42300/201642938-b2c3ec55-a616-484c-922b-0f0f2cd6de8f.png)

Also see PR #148 which adds support for both 3.10 and 3.11

**Comment by thomasleveil** [comment]
3.10 done in #99

**Comment by codespearhead** [comment]
Both PRs have been merged. Can this issue be closed?

**Comment by arks-public** [comment]
Now that Python 3.12 is the latest stable version, it would be cool if this project could add support for it.

**Comment by tiangolo** [comment]
Now that Uvicorn supports managing workers with `--workers`, including restarting dead ones, there's no need for Gunicorn. That also means that it's much simpler to build a Docker image from scratch now, I updated the docs to explain it.

Because of that, I deprecated this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image
