### ISSUE TITLE
[QUESTION] Not understanding the web concurrency going on

### ISSUE THREAD

**Issue by mr-bjerre** [tiangolo/uvicorn-gunicorn-docker#29]
First of all - I am not sure if this is this is the right place to ask. But you do have great documentation that brings production ready web applications available for people like me so I'm guessing there are others out there that are facing some of the same challenges like me.

### Context

I'm using a `FastAPI` application to trigger an ETL process which involves `spaCy` models as well. It is POST only, i.e. the application do not need to return any answer, it is used for "task triggering". Some times the application receive up to 30 post requests within 100 ms but it shouldn't add any delay compared to the case where a single statement arrives. So now I'm trying to figure out how to handle this properly - first steps for me is to understand the basics but I've stumpled upon a mystery to me.

### Example

I've made a simple application that sleeps for 3 seconds on any requests (and prints the time before and after the request)

`Dockerfile`
```Dockerfile
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8
ENV WEB_CONCURRENCY=1
ENV LOG_LEVEL="warning"

WORKDIR /app
COPY main.py .
```

`main.py`
```python
from time import sleep
import datetime
from fastapi import FastAPI
import logging

logging.basicConfig(level=logging.WARNING)

app = FastAPI()


def print_now(message: str):
    print(f"{datetime.datetime.now().strftime('%H:%M:%S')}: {message}")


def handle(i: int):
    print_now(f"Received {i}")
    sleep(3)
    print_now(f"Handled {i}")


@app.get("/")
def root(i: int):
    handle(i)
```

I've made a small test script that makes 100 requests at around the same time (each request made in a background thread)

`requests.sh`

```bash
#!/bin/bash
for i in {1..100}
do
   curl http://localhost/?i=${i} &
done
```

### Results

The current settings are (i.e. 1 worker)

    {"loglevel": "warning", "workers": 1, "bind": "0.0.0.0:80", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "80"}

Running `./requests.sh` then I see that my app handles max 30 requests at the same time (running on my macbook pro with 6 cores).

1. Why 30!?
2. If I change `def root(i: int):` to `async def root(i: int):` then my app handles 1 request per worker. Why is that different?
3. If I change the application to perform the task in a new thread then all requests are handled right away (until the machine is out of resources I assume), i.e.

```python
@app.get("/")
def root(i: int):
    t = threading.Thread(target=handle, args=(i,))
    t.daemon = True
    t.start()
```

3. but I feel like this is bad practice? 

I plan to have a load balancer in front but that doesn't change that the configurations on my containers should still be "right".

💥I think one of the "issues" here is that `FastAPI` is making it extremely easy for a guy like me (who doesn't know too much about gunicorn configurations, concurrency, async etc.) to (almost) make production ready web applications. I thank you for that! On a final note; is `FastAPI` even the right tool for this "task triggering" where speed is everything (100 ms differences is big)?

**Comment by tiangolo** [comment]
So, if you have several `def` functions that only wait there, they will block the thread they are in. And if you will still have a limited amount of threads, and if all of them are handling a request that is blocking with a sleep, then that will end up blocking the concurrency.

If you use `async` and `asyncio.sleep`, that "sleeps", but doesn't block and lets the rest of the code continue executing, without holding the resources. Because it is not really using the CPU, just waiting for something else.

But if you are doing something that is CPU intensive, like training a model, then you should probably still use `def` so that it runs in threadpool and doesn't block the rest, but if you run several of those at the same time, there will be a point where all your CPUs are used in full. And then it doesn't matter which tricks you use, your machine won't be able to handle more concurrency, just because all the CPU available is used.

Now, if that's the case and you are using something that is CPU intensive, if your use case is simple enough, and you expect a small concurrency, let's say, it's an internal tool used only by a small internal team, then it might be OK to just do it all internally in your FastAPI app.

But for anything bigger than that, you will probably end up needing to have more machines dedicating to training the models (or whatever is the slow resource-intensive task). And then your API would just receive requests and report the status of the training of those tasks, but the API code wouldn't be in charge of actually training the models.

Then, the way you would coordinate those different machines (or at least separate worker processes) would be with a tool like Celery or ARQ.

If you check the project generators, those have Celery setup and included by default.

If you want to try something new, I think ARQ is probably a very good option.

**Comment by mr-bjerre** [comment]
Thanks for the feedback. It makes sense!
