### ISSUE TITLE
Upgrade to Python 3.8.8 to fix CVE-2021-3177

### ISSUE THREAD

**Issue by cornjuliox** [tiangolo/uvicorn-gunicorn-docker#63]
Source: https://www.zdnet.com/article/python-programming-language-hurries-out-update-to-tackle-remote-code-vulnerability/

Hi, so we're using `tiangolo/uvicorn-gunicorn:python3.8` for one of our services right now, and we'd like to make sure that  they're all running Python 3.8.8 under the hood (as per the article above), but Poetry can't seem to pull anything greater than 3.8.6 when using either `tiangolo/uvicorn-gunicorn:python3.8` or `tiangolo/uvicorn-gunicorn:latest`.

Am I just using the wrong command or does a new image need to be pushed to Docker Hub? 

```Step 9/12 : RUN poetry install --no-root --no-dev
 ---> Running in 3dd3fb755f88
The currently activated Python version 3.8.6 is not supported by the project (3.8.8).
Trying to find and use a compatible version.

  NoCompatiblePythonVersionFound

  Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.```

**Comment by codespearhead** [comment]
The base image is set to pull the latest 3.8 version of Python, which currently is [3.8.18](https://hub.docker.com/_/python).

https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/49d3538121828a20f22b609c8278246e94a71d82/docker-images/python3.8-slim.dockerfile#L1

https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/49d3538121828a20f22b609c8278246e94a71d82/docker-images/python3.8.dockerfile#L1

Hence, this problem was solved as soon as a new minor version was published on DockerHub.

**Comment by tiangolo** [comment]
Thanks for the report @cornjuliox! And thanks for the comment @codespearhead! Indeed, this should be now automatically solved.

These images are now built automatically every week, so they should be continuously updated. :nerd_face:
